### PR TITLE
Bug/252 fix displayed workflow url

### LINKED ISSUE #252: RD prints URL of previous workflow
Instead of the URL of the currently running workflow, RD prints the URL of the previous workflow run.

```
$ release-droid -n exasol-test-setup-abstraction-server 
2022-08-11 16:44:54.458 [INFO   ] Validation started. 
2022-08-11 16:44:57.263 [INFO   ] Validation was performed without any problems! 
2022-08-11 16:44:57.299 [INFO   ] A full report is available: /Users/chp/.release-droid/last_report.txt 
chp@hw3782 ~ % release-droid -n exasol-test-setup-abstraction-server  -g release
2022-08-11 16:45:05.077 [INFO   ] There are no artifacts on the 'exasol/exasol-test-setup-abstraction-server' repository. 
2022-08-11 16:45:05.085 [INFO   ] Preparing a new artifact with a checksum. 
2022-08-11 16:45:06.462 [INFO   ] 16:45:06: Started GitHub workflow 'release_droid_prepare_original_checksum.yml': https://github.com/exasol/exasol-test-setup-abstraction-server/actions/runs/2670087736
```

The latest workflow is `https://github.com/exasol/exasol-test-setup-abstraction-server/actions/runs/2840660144`

### LINKED ISSUE #253: Support colored messages in windows console, too
Support colored messages in windows console, too: see https://github.com/fusesource/jansi

### PR DESCRIPTION
**Pull request by ckunki**
fixes #252 
fixes #253

### CODE REVIEW

File: src/main/java/com/exasol/releasedroid/formatting/Colorizer.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+    public static String red(final String text) {
+        return ansi().fgRed().a(text).reset().toString();
+    }
+
+    public static String green(final String text) {
+        return ansi().fgGreen().a(text).reset().toString();
+    }
+
+    public static String formatLink(final URL url) {
+        return ansi().fgBrightBlue().a(Attribute.UNDERLINE).a(url).reset().toString();
```
Comment (kaklakariada) [inline src/main/java/com/exasol/releasedroid/formatting/Colorizer.java:28]: 👍

**Review by kaklakariada — APPROVED** [review]
