### PR TITLE
* #159: Saved the release state.

### LINKED ISSUE #159: Save release state in case and re-start from the saved place in case the release failed
## Feature Description

We want to save the release state in case the release failed on some step and continue from the same place after re-starting the release droid.

### PR DESCRIPTION
**Pull request by AnastasiiaSergienko**
Closes #159

### CODE REVIEW

File: src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java [hunk 1]
```diff
@@ -69,33 +70,72 @@ private void logResults(final Report releaseReport) {
...
+            LOGGER.info(() -> "Nothing to release. The release has been already performed on all mentioned platforms.");
+        }
+        return report;
+    }
+
+    private Set<PlatformName> getAlreadyReleasedPlatforms(final String repositoryName, final String releaseVersion) {
+        return this.releaseState.getProgress(repositoryName, releaseVersion);
+    }
+
+    private boolean unreleasedPlatformsPresent(final List<PlatformName> platforms, final Set<PlatformName> released) {
```
Comment (chiaradiamarcelo) [inline src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java:86]:
```suggestion
    private boolean areUnreleasedPlatformsPresent(final List<PlatformName> platforms, final Set<PlatformName> released) {
```

File: src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java [hunk 2]
```diff
@@ -69,33 +70,72 @@ private void logResults(final Report releaseReport) {
...
+        this.releaseState.saveProgress(repository.getName(), repository.getVersion(), platformName);
+    }
+
     private void prepareRepositoryForRelease(final Repository repository) {
         this.releaseManager.prepareForRelease(repository);
     }
 
-    private void cleanRepositoryAfterRelease(final Repository repository, final Report report) {
-        if (!report.hasFailures()) {
+    private void cleanRepositoryAfterRelease(final Repository repository, final boolean hasFailures) {
```
Comment (chiaradiamarcelo) [inline src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java:137]: I find this name confusing, as it does not match always to what the method does (i.e. sometimes the repo is clean but some others not). I would suggest to either rename the or the move the if clause outside

Comment (chiaradiamarcelo) [inline src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java:137]: I would also suggest to avoid using boolean parameters in this way

File: src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java [hunk 3]
```diff
@@ -69,33 +70,72 @@ private void logResults(final Report releaseReport) {
 
     private Report makeRelease(final Repository repository, final List<PlatformName> platforms) {
         final var report = Report.releaseReport();
+        final Set<PlatformName> released = getAlreadyReleasedPlatforms(repository.getName(), repository.getVersion());
```
Comment (chiaradiamarcelo) [inline src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java:73]:
```suggestion
        final Set<PlatformName> releasedPlatforms = getAlreadyReleasedPlatforms(repository.getName(), repository.getVersion());
```

File: src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java [hunk 4]
```diff
@@ -69,33 +70,72 @@ private void logResults(final Report releaseReport) {
...
         final Report report = Report.releaseReport();
         for (final PlatformName platformName : platforms) {
-            LOGGER.info(() -> "Releasing on " + platformName + " platform.");
-            try {
-                this.getReleaseMaker(platformName).makeRelease(repository);
-                report.addResult(ReleaseResult.successfulRelease(platformName));
-            } catch (final ReleaseException exception) {
-                report.addResult(ReleaseResult.failedRelease(platformName, ExceptionUtils.getStackTrace(exception)));
-                break;
+            if (released.contains(platformName)) {
```
Comment (chiaradiamarcelo) [inline src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java:102]: would be nice to move this outside this method to be consistent and match the semantic of the method with its name

File: src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java [hunk 5]
```diff
@@ -69,33 +70,72 @@ private void logResults(final Report releaseReport) {
 
     private Report makeRelease(final Repository repository, final List<PlatformName> platforms) {
         final var report = Report.releaseReport();
+        final Set<PlatformName> released = getAlreadyReleasedPlatforms(repository.getName(), repository.getVersion());
+        if (unreleasedPlatformsPresent(platforms, released)) {
+            report.merge(release(repository, platforms, released));
```
Comment (chiaradiamarcelo) [inline src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java:75]: would be nice to decide here which platforms should be released

File: src/main/java/com/exasol/releasedroid/usecases/release/ReleaseState.java [hunk 6]
```diff
@@ -0,0 +1,118 @@
...
+import java.util.Locale;
+import java.util.Set;
+import java.util.stream.Stream;
+
+import com.exasol.errorreporting.ExaError;
+import com.exasol.releasedroid.usecases.exception.ReleaseException;
+import com.exasol.releasedroid.usecases.request.PlatformName;
+
+/**
+ * This class responsible for the release state.
```
Comment (chiaradiamarcelo) [inline src/main/java/com/exasol/releasedroid/usecases/release/ReleaseState.java:19]:
```suggestion
 * This class is responsible for the release state.
```
