### PR TITLE
#264 implemented

### LINKED ISSUE #264: Unspecified language: Add hint to enhance file release_config.yml
Add hint to enhance file `release_config.yml`

Current error message
```
[WARNING] The repository language was detected automatically: JAVA. If it
was detected incorrectly, please specify it manually using -lg <language> argument.
```
#### Proposed error message: 
```
[WARNING] W-RD-REP-xxx: The repository language was detected automatically: JAVA. If it
was detected incorrectly, please add language: <language> to file release_config.yml or specify it manually using argument -lg <language>.
```

### PR DESCRIPTION
**Pull request by ckunki**
fixes #264

### CODE REVIEW

File: src/main/java/com/exasol/releasedroid/adapter/repository/RepositoryFactory.java [hunk 1]
```diff
@@ -83,8 +85,12 @@ private Language githubPrimaryLanguage(final UserInput userInput) {
                     .getRepositoryPrimaryLanguage(userInput.getFullRepositoryName());
             validateLanguage(repositoryPrimaryLanguage);
             final var language = Language.getLanguage(repositoryPrimaryLanguage);
-            LOGGER.warning(() -> "The repository language was detected automatically: " + language
-                    + ". If it was detected incorrectly, please specify it manually using -lg <language> argument.");
+            LOGGER.warning(() -> ExaError.messageBuilder("W-RD-REP-34") //
+                    .message("The repository language was detected automatically as {{language}}.", language.name())
+                    .mitigation("If incorrect then please add {{entry|uq}} to file {{file|uq}}" //
+                            + " or use command line argument {{cli|uq}}.", //
+                            code("language: <language>"), code("release_config.yml"), code("-lg <language>"))
```
Comment (morazow) [inline src/main/java/com/exasol/releasedroid/adapter/repository/RepositoryFactory.java:92]: :+1: 

Wow, I did not know about the `code` options, it is very nice!

File: src/main/java/com/exasol/releasedroid/formatting/Colorizer.java [hunk 2]
```diff
@@ -39,4 +39,8 @@ public static String brightGreen(final String s) {
     public static String yellow(final String s) {
         return ansi().fgBrightYellow().a(s).reset().toString();
     }
+
+    public static String code(final String s) {
+        return ansi().fgBrightCyan().a(s).reset().toString();
+    }
```
Comment (morazow) [inline src/main/java/com/exasol/releasedroid/formatting/Colorizer.java:45]: :+1:

**Review by morazow — APPROVED** [review]
