### PR TITLE
#228 Implemented

### LINKED ISSUE #228: Add support for Maven projects with multiple modules
Maven projects with multiple modules like [project-keeper](https://github.com/exasol/project-keeper) are currently not supported by release-droid.

Currently for project-keeper release-droid issues the follwing messages
*    Project URL is missing in the pom.xml file. [For platforms: MAVEN]
*    Project description is missing in the pom.xml file. [For platforms: MAVEN]
*    E-RD-REP-15: Required maven plugin is missing: 'project-keeper-maven-plugin'. [For platforms: MAVEN,GITHUB]

Hint:
Combine with #243

### LINKED ISSUE #230: Add info to documentation
Some information is missing/outdated in the documentation:
- Add a note about problems that arise with the users Jira password:
- - special character in pw
- - jira pw to long

These result in getting an access "forbidden" message from Jira. Can be fixed by changing the Jira password.

- info on --platforms in the command line parameter table shows deprecated format, not new format mentioned below. Updating this might be better for consistency. 

(Also, `-platforms github jira` works without the comma. Check if this is intended?)

### LINKED ISSUE #231: Configure project language in release_config.yml
Instead of always specifying the project language (java, generic, ...) on the command line it would save time to configure the language in `release_config.yml` only once.

### LINKED ISSUE #238: Optionally accept credentials only from config file ~/.release-droid/credentials incl. fail fast
Preferred use case in my eyes is to store credentials in config file `~/.release-droid/credentials`.
I propose to enable users to make RD accept credentials only from there.
This enables the benefit to check the file first and to fail in an early point in time if credentials are missing.

Later on we could think of another feature "verify-credentials"

### PR DESCRIPTION
**Pull request by ckunki**
fixes #228 multi module maven 
fixes #230 user_guide: command line parameters 
fixes #238 warn on missing file credentials
fixes #231 configure project language in file `release_config.yml`

### CODE REVIEW

File: src/test/java/com/exasol/releasedroid/adapter/repository/RepositoryFactoryTest.java [hunk 1]
```diff
@@ -4,9 +4,14 @@
 import static org.hamcrest.MatcherAssert.assertThat;
 import static org.hamcrest.Matchers.containsString;
 import static org.hamcrest.Matchers.instanceOf;
+//import static org.hamcrest.Matchers.*;
```
Comment (pj-spoelders) [inline src/test/java/com/exasol/releasedroid/adapter/repository/RepositoryFactoryTest.java:7]:
```suggestion
```
Please remove this commented out import line.

**Review by pj-spoelders — CHANGES_REQUESTED** [review]
1 minor suggestion

**Review by pj-spoelders — APPROVED** [review]
