### PR TITLE
* #150: Refactored validations

### LINKED ISSUE #66: Decouple GitRepositoryValidatorTest from the production code
Currently the tests are tightly coupled with the production code, and whenever we want to clean up the code we need to change the tests after it and hope we didn't break anything in the process.

We should decouple it, change the private/protected test method for testcases through the production code's public API.

We probably also need an adapter to deal with this API from the tests.

### LINKED ISSUE #150: CommunityPortal release shouldn't fail because of the version validation
## Problem

If we publish a release on GitHub and then run the CommunityPortal release, it fails because it validates a version and says that it exists already: `The new version '2.0.0' does not fit the versioning rules`.

It should check that the GitHub Release exists instead.

### PR DESCRIPTION
**Pull request by AnastasiiaSergienko**
Closes #150 
Closes #66

### CODE REVIEW

File: src/main/java/com/exasol/releasedroid/usecases/validate/StructureValidator.java [hunk 1]
```diff
@@ -5,9 +5,9 @@
 /**
  * This interface provides repository-related validations.
  */
-public interface RepositoryValidator {
+public interface StructureValidator {
```
Comment (chiaradiamarcelo) [inline src/main/java/com/exasol/releasedroid/usecases/validate/StructureValidator.java:8]: I find it a bit hard to understand what's the purpose of the interface is just by looking at the name.
Maybe we can roll this back

File: src/main/java/com/exasol/releasedroid/adapter/github/RepositoryStructureValidator.java [hunk 2]
```diff
@@ -9,75 +12,78 @@
...
 
 /**
- * Contains validations for a Git project.
+ * Contains validations for a repository structure.
  */
-public class GitHubRepositoryValidator extends AbstractRepositoryValidator {
-    private static final Logger LOGGER = Logger.getLogger(GitHubRepositoryValidator.class.getName());
-    protected static final String PREPARE_ORIGINAL_CHECKSUM_WORKFLOW_PATH = ".github/workflows/release_droid_prepare_original_checksum.yml";
-    protected static final String PRINT_QUICK_CHECKSUM_WORKFLOW_PATH = ".github/workflows/release_droid_print_quick_checksum.yml";
+public class RepositoryStructureValidator implements StructureValidator {
```
Comment (chiaradiamarcelo) [inline src/main/java/com/exasol/releasedroid/adapter/github/RepositoryStructureValidator.java:24]: Maybe we can call this by it's distinctive factor, as these validations have to pass for every repository on top of the specific ones  (Java, Scala, Python).
Maybe something like `CommonRepositoryValidator` or `ReleasableRepositoryValidator` or something similar?

**Review by chiaradiamarcelo — APPROVED** [review]
Looks great! I left some small comments

**Review by chiaradiamarcelo — APPROVED** [review]
