### PR TITLE
* #192: Made the config file optional for Jira release.

### LINKED ISSUE #192: Only check a project name in the config file when the file is present
## Problem

Having a config file is optional, but the release droid fails when it can't find the file.

### PR DESCRIPTION
**Pull request by AnastasiiaSergienko**
Closes #192

### CODE REVIEW

File: src/main/java/com/exasol/releasedroid/adapter/jira/JiraReleaseMaker.java [hunk 1]
```diff
@@ -55,16 +53,14 @@ private String createTicketRequest(final Repository repository) throws JiraExcep
...
 
     private String getHumanReadableName(final Repository repository) {
-        final String projectNameFromConfig = getProjectNameFromConfig(repository);
-        if (projectNameFromConfig != null) {
-            return projectNameFromConfig;
-        } else {
-            return getDefaultProjectName(repository.getName());
-        }
+        final Optional<String> projectNameFromConfig = getProjectNameFromConfig(repository);
+        return projectNameFromConfig.orElseGet(() -> getDefaultProjectName(repository.getName()));
```
Comment (tomuben) [inline src/main/java/com/exasol/releasedroid/adapter/jira/JiraReleaseMaker.java:57]: Not 100%, bu I think this can be simplified to:
```suggestion
        return projectNameFromConfig.orElse(getDefaultProjectName(repository.getName()));
```

Comment (AnastasiiaSergienko) [reply src/main/java/com/exasol/releasedroid/adapter/jira/JiraReleaseMaker.java:57]: `orElse` takes a variable/constant and `orElseGet` takes a Supplier(lambda function). So in this case I can't use `orElse` as I call a function from it.

Comment (tomuben) [reply src/main/java/com/exasol/releasedroid/adapter/jira/JiraReleaseMaker.java:57]: Hm, I think I see my mistake. orElse() would always evaluate the expression (always would call getDefaultProjectName(...)), even if the Optional is not empty.

**Review by tomuben — APPROVED** [review]

**Review by tomuben — APPROVED** [review]
