### PR TITLE
* #134: Fixed parsing of the plugins in the pom file.

### LINKED ISSUE #134: Consider possible missing version in the plugins parsing

### PR DESCRIPTION
**Pull request by AnastasiiaSergienko**
Closes #134

### CODE REVIEW

File: src/main/java/com/exasol/releasedroid/maven/MavenPluginValidator.java [hunk 1]
```diff
@@ -56,16 +56,18 @@ public Report validatePluginVersionEqualOrGreater(final String pluginName, final
 
     private Report validatePluginVersion(final String pluginName, final String expectedVersion) {
         final Report report = Report.validationReport();
-        final String actualVersion = this.plugins.get(pluginName).getVersion();
-        if (compareSemanticVersion(expectedVersion, actualVersion)) {
+        final MavenPlugin plugin = this.plugins.get(pluginName);
+        final String actualVersion = plugin.getVersion();
+        if (plugin.hasVersion() && compareSemanticVersion(expectedVersion, actualVersion)) {
```
Comment (jakobbraun) [inline src/main/java/com/exasol/releasedroid/maven/MavenPluginValidator.java:61]: you check the version here after you run getVersion(). I would expect that if it's null the get will fail somehow. The tests prove however, that it's not the case...

**Review by jakobbraun — APPROVED** [review]

File: src/main/java/com/exasol/releasedroid/maven/MavenPluginValidator.java (hunk 1 above)
Comment (AnastasiiaSergienko) [reply src/main/java/com/exasol/releasedroid/maven/MavenPluginValidator.java]: I've inline the variable to avoid confusions
