### PR TITLE
#89: Fix false positive validation for open ticket

### LINKED ISSUE #89: False positive validation for open ticket
Issues mentioned in the summary should not be checked for being closed.

Example:

I mentioned in the Summary a known issue. So a bug that is still open and will not fixed by this release.
The release-droid refuses to release since the ticket was not closed.

### PR DESCRIPTION
**Pull request by chiaradiamarcelo**
Close #89.

### CODE REVIEW

**Comment by jakobbraun** [comment]
add labels anmd project to this PR

File: src/main/java/com/exasol/releasedroid/repository/ReleaseLetterParser.java [hunk 1]
```diff
@@ -104,7 +104,7 @@ private String parseHeader(final String headerPart) {
         final List<String> hashtags = getExpressionsByRegex(body, TICKET_NUMBER_REGEX);
         final List<Integer> numbers = new ArrayList<>();
         for (final String hashtag : hashtags) {
-            final int ticketNumber = Integer.parseInt(hashtag.substring(1));
+            final int ticketNumber = Integer.parseInt(hashtag.substring(3));
```
Comment (jakobbraun) [inline src/main/java/com/exasol/releasedroid/repository/ReleaseLetterParser.java:107]: I think using a capture group for the regex would be the nicer solution here.

Comment (jakobbraun) [reply src/main/java/com/exasol/releasedroid/repository/ReleaseLetterParser.java:107]: But it's also ok like that.

**Review by jakobbraun — APPROVED** [review]
approved with a suggestion
